### PR TITLE
feature: ability to specify a lockscreen app that gets run when the session is locked

### PR DESCRIPTION
**Pull request by mattkae**
## How to test
1. Run Miriway with `./miriway --lockscreen-app=swaylock`
2. `loginctl lock-session <ID>`
3. Note that your session is locked
4. Enter your password in swaylock **or** `loginctl unlock-session <ID>` (**WARNING**: With `swaylock`, using `loginctl` to unlock will send you into a lockscreen-forever-loop, because Miriway sees swaylock exiting with status `2`, causing us to restart it over and over again. I have a pull request opened on that project to theoretically fix this)
5. Note that your session is unlocked

**WARNING**: This relies on this branch of Mir to work: https://github.com/canonical/mir/pull/3232

### CODE REVIEW

File: miriway.cpp [hunk 1]
```diff
@@ -94,9 +95,25 @@ struct ShellComponents
...
+
+    void launch_lockscreen() const
+    {
+        if (lockscreen_app.has_value())
+            launch(lockscreen_app.value());
+    }
 private:
     std::function<void (std::vector<std::string> const& command_line)> const launch;
     std::vector<std::vector<std::string>> commands;
+    std::optional<std::vector<std::string>> lockscreen_app;
```
Comment (AlanGriffiths) [inline miriway.cpp:116]: There's only zero or one lockscreen_app

```suggestion
    std::optional<std::string> lockscreen_app;
```

File: miriway.cpp [hunk 2]
```diff
@@ -94,9 +95,25 @@ struct ShellComponents
...
+
+        lockscreen_app = cmd;
+        return true;
+    }
+
+    void launch_lockscreen() const
+    {
+        if (lockscreen_app.has_value())
+            launch(lockscreen_app.value());
+    }
```
Comment (AlanGriffiths) [inline miriway.cpp:112]: I can't help feeling there's no reason to insert this logic into `ShellComponents`.

A `LockScreen` class could own everything: the option and result, the `SessionLockListener`, the registration with ShellPids, adding the Wayland extension. Something like this...

```c++
class  LockScreen
{
public:
    explicit LockScreen(std::function<void>(std::string name) conditionally_enable)
    (
        conditionally_enable(WaylandExtensions::ext_session_lock_manager_v1);
    }

    void operator()(mir::Server& server) const
    {
        lockscreen_option(server);
        session_locker(server);
    }

private:
    std::optional<std::string> lockscreen_app;
    
    ConfigurationOption const lockscreen_option{
        [this](std::string const& app) {
            lockscreen_app = app;
        }

        "lockscreen-app",
        "Lockscreen app to be triggered when the compositor session is locked (may only be specified once)"
    };

    SessionLockListener const session_locker(
            [this] { if (lockscreen_app) shell_launch( split_command(*lockscreen_app)); },
            [] {});
};
```

**Review by AlanGriffiths — CHANGES_REQUESTED** [review]
This will not land unless it builds against the latest Mir release: `miral/version.h` provides a way to `#if` code that is version dependent

File: miriway.cpp (hunk 2 above)
Comment (mattkae) [reply miriway.cpp:112]: Implemented. Feels a lot better

File: miriway.cpp [hunk 3]
```diff
@@ -99,6 +119,42 @@ struct ShellComponents
...
+    {
+        lockscreen_option(server);
+        session_locker(server);
+    }
+
+private:
+    ConfigurationOption const lockscreen_option;
+    SessionLockListener const session_locker;
+    std::optional<std::string> lockscreen_app;
+};
```
Comment (AlanGriffiths) [inline miriway.cpp:156]: Several things:

1. Capturing constructor args _by reference_ won't work for the SessionLocker callback
2. Please use uniform initialization syntax

I shuffled the code a little to reduce the #ifs:

```suggestion
class LockScreen
{
public:
    explicit LockScreen(
        std::function<void(std::vector<std::string> const& command_line)> launch,
        std::function<void(std::string name)> const& conditionally_enable) : 
            launch{std::move(launch)},
            lockscreen_option{[this](mir::optional_value<std::string> const& app) {
                    if (app.is_set())
                    {
#if MIRAL_VERSION < MIR_VERSION_NUMBER(5, 0, 0)
                        mir::log_warning("SessionLockListener is not available before miral 5.0");
#endif
                        lockscreen_app = app.value();
                    }
                },
                "lockscreen-app",
                "Lockscreen app to be triggered when the compositor session is locked"
          }
    {
        conditionally_enable(WaylandExtensions::ext_session_lock_manager_v1);
    }

    void operator()(mir::Server& server) const
    {
        lockscreen_option(server);
        session_locker(server);
    }

private:
    std::function<void(std::vector<std::string> const& command_line)> const launch;
    ConfigurationOption const lockscreen_option;
#if MIRAL_VERSION >= MIR_VERSION_NUMBER(5, 0, 0)
    SessionLockListener const session_locker{
              [this]{ if (lockscreen_app) launch(ExternalClientLauncher::split_command(*lockscreen_app)); },
              [] {}
          };
#eise
      auto const session_locker = [](mir::Server&){};
#endif
    std::optional<std::string> lockscreen_app;
};
#endif
```

**Review by AlanGriffiths — CHANGES_REQUESTED** [review]

**Comment by mattkae** [comment]
Maybe the stanza should be 5.1, right @AlanGriffiths ?

**Comment by AlanGriffiths** [comment]
> Maybe the stanza should be 5.1, right @AlanGriffiths ?

No. You can see that the CMake build works with 4.1 (from Mir 2.16). The Snap action patches the snapcraft.yaml to use `ppa:mir-team/dev` which doesn't yet have https://github.com/canonical/mir/pull/3232 (even though ti is 5.0

**Comment by Saviq** [comment]
Toggled so we get a newer build

**Comment by Saviq** [comment]
Ruh roh?

```
:: /root/parts/miriway/src/miriway.cpp:38:10: fatal error: miral/session_lock_listener.h: No such file or directory
::    38 | #include <miral/session_lock_listener.h>
::       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by mattkae** [comment]
> Ruh roh?
> 
> ```
> :: /root/parts/miriway/src/miriway.cpp:38:10: fatal error: miral/session_lock_listener.h: No such file or directory
> ::    38 | #include <miral/session_lock_listener.h>
> ::       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```

But... the CI built? :eyes: Is this local?

**Comment by Saviq** [comment]
> But... the CI built? 👀 Is this local?

Aaah, that was the old run :facepalm:

GitHub not helping.

File: miriway.cpp [hunk 4]
```diff
@@ -197,8 +243,9 @@ struct ShellPids
 
                     if (auto it = shell_component_pids.find(pid); it != shell_component_pids.end())
                     {
-                        if (status)
+                        if (WIFEXITED(status) && WEXITSTATUS(status))
                         {
+                            mir::log_info("Process exited with status: %d", WEXITSTATUS(status));
```
Comment (AlanGriffiths) [inline miriway.cpp:248]: Who is this "info" for? It looks uninformative ("what process?") and unnecessary

File: miriway.cpp [hunk 5]
```diff
@@ -197,8 +243,9 @@ struct ShellPids
 
                     if (auto it = shell_component_pids.find(pid); it != shell_component_pids.end())
                     {
-                        if (status)
+                        if (WIFEXITED(status) && WEXITSTATUS(status))
```
Comment (AlanGriffiths) [inline miriway.cpp:246]: We likely want to handle `WIFSIGNALED/WTERMSIG` too

File: miriway.cpp [hunk 6]
```diff
@@ -415,6 +462,10 @@ int main(int argc, char const* argv[])
             alt,
             Keymap{},
             AppendEventFilter{[&](MirEvent const* e) { return commands.input_event(e); }},
-            set_window_management_policy<WindowManagerPolicy>(commands)
+            set_window_management_policy<WindowManagerPolicy>(commands),
+            LockScreen(
+                [&shell_launch](auto const& cmd) { shell_launch(cmd, std::make_shared<ShellComponentRunInfo>()); },
+                [&extensions, &enable_for_shell_pids](auto protocol) {
+                    extensions.conditionally_enable(protocol, enable_for_shell_pids); })
```
Comment (AlanGriffiths) [inline miriway.cpp:469]: I think this construction is elaborate enough to "extract variable".

File: miriway.cpp [hunk 7]
```diff
@@ -99,6 +103,48 @@ struct ShellComponents
...
+                {
+    #if MIRAL_VERSION < MIR_VERSION_NUMBER(5, 0, 0)
+                    mir::log_warning("SessionLockListener is not available before miral 5.0");
+    #endif
+                    lockscreen_app = ExternalClientLauncher::split_command(app.value());
+                }
+            },
+      "lockscreen-app",
+      "Lockscreen app to be triggered when the compositor session is locked"
+        }
```
Comment (AlanGriffiths) [inline miriway.cpp:125]: Weird indentation

**Review by AlanGriffiths — CHANGES_REQUESTED** [review]
Some tidy-up required

**Review by AlanGriffiths — CHANGES_REQUESTED** [review]
This doesn't work as documented, nor as I expected. Testing with:

```
snap refresh --channel=edge/pr90 miriway
```

>     1. Run Miriway with `./miriway --lockscreen-app=waybar`

This seems to be a wrong app, I added the following to miriway.config:

```
shell-ctrl-alt=l:miriway-unsnap swaylock -i /usr/share/backgrounds/warty-final-ubuntu.png
lockscreen-app=miriway-unsnap swaylock -i /usr/share/backgrounds/warty-final-ubuntu.png
```

>     2. `loginctl lock-session <ID>`
I opened a terminal and ran:
```
loginctl lock-session
```

>     3. Note that your session is locked

The screen blanks, but swaylock _doesn't_ show.

However, pressing `Ctrl-Alt-L` to launch swaylock _does_ show swaylock.

>     4. Enter your password in swaylock

That works

>     5. Note that your session _is still locked_ because logind holds the lock

What does "_is still locked_" mean? The session is working fine.

>     6. `loginctl lock-session <ID>`

Should that be `loginctl unlock-session`?

>     7. Note that your session is unlocked


Now, another scenario:

```
loginctl lock-session; sleep 5; loginctl unlock-session
```

This leads to a session where something has gone wrong with keyboard input (probably focus): typing does not appear in the terminal (even though it appears focussed). The mouse can select text in the terminal, but still no keyboard input. Switching workspaces does work, and after switching back keyboard input is restored. 

**Summary**

1. the instructions show the wrong lockscreen app
2. the lockscreen app isn't shown
3. "Note that your session _is still locked_" doesn't seem to be true (nor desirable?)
4. the instructions show the wrong unlock command
5. Keyboard input isn't restored correctly after `loginctl unlock-session`

Some of this may need fixing in Mir, but we shouldn't be landing this PR unless the feature works as expected.

**Comment by AlanGriffiths** [comment]
> * the lockscreen app isn't shown

This is weird: the laptop I tested on had been used to try Lomiri (which had uninstalled GDM in favour of LightDM). After purging some Lomiri stuff and bringing GDM back, swaylock was shown at this point.

> * Keyboard input isn't restored correctly after `loginctl unlock-session`

This is no longer a problem either - we get swaylock restarting (known issue), but that accepts the password and keyboard focus is normal afterwards.

We probably still want to understand these failure modes, but they are not blockers.

**Comment by AlanGriffiths** [comment]
Another scenario: Lock the screen (either via `loginctl` or `Ctrl-Alt-L`).

Expect: Miriway's configured commands are disabled.
Actual: Miriway's commands still work. E.g. `Ctrl-Alt-T` launches a terminal; `Meta-PgDn` switches workspace; and, `Ctrl-Alt-Shift-BkSp` forces a logout.

**Comment by Saviq** [comment]
> `Ctrl-Alt-Shift-BkSp` forces a logout.

FWIW, I sometimes miss this in GNOME ;)

**Comment by Saviq** [comment]
> Run Miriway with `./miriway --lockscreen-app=waybar`

I think this was supposed to be `swaylock`?

**Comment by AlanGriffiths** [comment]
> > Run Miriway with `./miriway --lockscreen-app=waybar`
> 
> I think this was supposed to be `swaylock`?

So do I (see above)

**Comment by mattkae** [comment]
@AlanGriffiths : I updated the instructions in the comment. They were outdated, sorry! The bugs that you found are still valid though. I'll see if I can hunt them down

**Comment by mattkae** [comment]
Created a bug to address the key commands issue: https://github.com/canonical/mir/issues/3268

**Comment by AlanGriffiths** [comment]
> Created a bug to address the key commands issue: [canonical/mir#3268](https://github.com/canonical/mir/issues/3268)

That may be the wrong place: see `miriway::ShellCommands::shell_commands_active`.

**Comment by mattkae** [comment]
> > Created a bug to address the key commands issue: [canonical/mir#3268](https://github.com/canonical/mir/issues/3268)
> 
> That may be the wrong place: see `miriway::ShellCommands::shell_commands_active`.

@AlanGriffiths But would we want to inhibit _any_ window manager policy from processing key commands while the session is locked?

**Comment by mattkae** [comment]
As Alan and I discussed, you should use the following to avoid bugs in the lockscreen loop:

```
shell-ctrl-alt=l:miriway-unsnap loginctl lock-session <SESSION_ID>
lockscreen-app=miriway-unsnap swaylock -i /usr/share/backgrounds/warty-final-ubuntu.png
```

**Comment by mattkae** [comment]
Made this bug too, since I've seen this before: https://github.com/canonical/mir/issues/3269

**Comment by AlanGriffiths** [comment]
> @AlanGriffiths But would we want to inhibit _any_ window manager policy from processing key commands while the session is locked?

The shell is appending (or, in theory, prepending) an event filter, and only that ls deciding whether events are shell commands. You're suggesting that the filter is disabled in Mir?

**Comment by AlanGriffiths** [comment]
Building against 2.16.3 is failing

```
/home/runner/work/Miriway/Miriway/miriway.cpp: In function ‘int main(int, const char**)’:
/home/runner/work/Miriway/Miriway/miriway.cpp:478:13: error: ‘SessionLockListener’ was not declared in this scope
  478 |             SessionLockListener(
      |             ^~~~~~~~~~~~~~~~~~~
```

File: miriway.cpp [hunk 8]
```diff
@@ -466,8 +467,16 @@ int main(int argc, char const* argv[])
             meta,
             alt,
             Keymap{},
-            AppendEventFilter{[&](MirEvent const* e) { return commands.input_event(e); }},
+            AppendEventFilter{[&](MirEvent const* e) {
+                if (is_locked)
+                    return false;
+
+                return commands.input_event(e);
+            }},
```
Comment (AlanGriffiths) [inline miriway.cpp:475]:
```suggestion
            AppendEventFilter{[&](MirEvent const* e) {
                if (is_locked)
                    return false;

                return commands.input_event(e);
            }},
#if MIRAL_VERSION >= MIR_VERSION_NUMBER(5, 0, 0)
            SessionLockListener(
                [&] { is_locked = true; },
                [&] { is_locked = false; })
        });
#endif
```
